M48
; DRILL file {KiCad 9.0.7+1} date 2026-04-25T03:33:35+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-25T03:33:35+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7+1
; #@! TF.FileFunction,Plated,1,6,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.200
%
G90
G05
T1
X151.0Y-80.0
X153.54Y-80.0
T2
X159.22Y-88.78
X180.773Y-67.227
M30
